### ISSUE TITLE
Valitun templaatin esittäminen templaattikirjastossa

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/arho-feature-template#23]
Nyt templaatin voi valita listasta klikkaamalla riviä, mutta valinnalla ei ole merkitystä. Aktiivinen templaatti valitaan checkboxin avulla, mutta työkalun vaihtaminen pois digitoinnista ei myöskään poista checkboxista valintaa.

Olisiko intuitiivista ja selkeämpää, että listan riveillä ei olisi checkboxeja, vaan rivin valitseminen klikkaamalla johtaisi suoraan templaatin ja digitoinnin aktivointiin? Sen lisäksi, jos käyttäjä vaihtaa työkalua ja siten deaktivoi digitoinnin, rivin valinta poistettaisiin samalla.

**Comment by nmaarnio** [comment]
Onko ajatuksia tästä @LKajan ?

**Comment by LKajan** [comment]
No näin sen olin alunperin ajatellutkin ja (toteuttanutkin), että toimisi pelkällä valinnalla. Sitten lähdin ehkä turhan monimutkaisesti miettimään, että pitäisikö olla vahvempi interaktio templaatin valintaan ja miten listaa voi navigoida näppiksellä (nuolilla valinta ja check enterillä). Mutta ehkä tosiaan tuo pelkkä valinta on selkeämpi. Nyt on vähän sekava, että on valinta ja check erikseen.
