### ISSUE TITLE
Uusi kaava -lomakkeen uudelleen suunnittelu/toteutus

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/arho-feature-template#44]
Uutta kaavaa luotaessa lomakkeella halutaan näkyvän vain tarvittavat tiedot.

Huomioi, että lomakkeella halutaan mahdollisesti jatkossa lisätä myös yleismääräyksiä (kaavamääräysryhmiä).

**Comment by rlindb** [comment]
Suunnitelmakuvia:
![Näyttökuva 2024-11-19 123504](https://github.com/user-attachments/assets/85dd075d-aea2-44eb-9c4c-282d5bd6bca3)
![Näyttökuva 2024-11-19 124059](https://github.com/user-attachments/assets/cd6c8b7a-3a2b-4ed7-af10-00e51f8973ca)
![Näyttökuva 2024-11-19 124129](https://github.com/user-attachments/assets/da6a7abb-aea8-40a5-a4fc-f134728c97c9)

- Organisaatio => tietokannasta tieto
- Tuottajan kaavatunnus. Jos pysyvätunnus on tarpeeksi selkeä, niin tätä ei tarvitse.
- Elinkaaren tila  & vireilletulopvm: Pakko olla vähintään vireilletulopvm. => tästä tallentuu päivämäärä, jos luodaan vireilletullut kaava.
- Vastuutaho => minimitiedoilla, eli ne mitä Ryhti vaatii, nimiä ei ehkä ole tarve laittaa tietokantaan, koska ne tulevat kaavaselostukseen
- Pysyvä kaavatunnus-> tämä pitäisi saada heti kun kaava tulee vireille.
- Voisiko liitteet ja lähtötietoaineistot olla samassa näkymässä.

Olisiko näitä kuvia vielä mahdollista selkeyttää? Nyt on paljon asiaa ja paljon välilehtiä.
